require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Location::DestinationsController do

  # This should return the minimal set of attributes required to create a valid
  # Location::Destination. As you add validations to Location::Destination, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Location::DestinationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all location_destinations as @location_destinations" do
      destination = Location::Destination.create! valid_attributes
      get :index, {}, valid_session
      assigns(:location_destinations).should eq([destination])
    end
  end

  describe "GET show" do
    it "assigns the requested location_destination as @location_destination" do
      destination = Location::Destination.create! valid_attributes
      get :show, {:id => destination.to_param}, valid_session
      assigns(:location_destination).should eq(destination)
    end
  end

  describe "GET new" do
    it "assigns a new location_destination as @location_destination" do
      get :new, {}, valid_session
      assigns(:location_destination).should be_a_new(Location::Destination)
    end
  end

  describe "GET edit" do
    it "assigns the requested location_destination as @location_destination" do
      destination = Location::Destination.create! valid_attributes
      get :edit, {:id => destination.to_param}, valid_session
      assigns(:location_destination).should eq(destination)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Location::Destination" do
        expect {
          post :create, {:location_destination => valid_attributes}, valid_session
        }.to change(Location::Destination, :count).by(1)
      end

      it "assigns a newly created location_destination as @location_destination" do
        post :create, {:location_destination => valid_attributes}, valid_session
        assigns(:location_destination).should be_a(Location::Destination)
        assigns(:location_destination).should be_persisted
      end

      it "redirects to the created location_destination" do
        post :create, {:location_destination => valid_attributes}, valid_session
        response.should redirect_to(Location::Destination.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved location_destination as @location_destination" do
        # Trigger the behavior that occurs when invalid params are submitted
        Location::Destination.any_instance.stub(:save).and_return(false)
        post :create, {:location_destination => {  }}, valid_session
        assigns(:location_destination).should be_a_new(Location::Destination)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Location::Destination.any_instance.stub(:save).and_return(false)
        post :create, {:location_destination => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested location_destination" do
        destination = Location::Destination.create! valid_attributes
        # Assuming there are no other location_destinations in the database, this
        # specifies that the Location::Destination created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Location::Destination.any_instance.should_receive(:update_attributes).with({ "these" => "params" })
        put :update, {:id => destination.to_param, :location_destination => { "these" => "params" }}, valid_session
      end

      it "assigns the requested location_destination as @location_destination" do
        destination = Location::Destination.create! valid_attributes
        put :update, {:id => destination.to_param, :location_destination => valid_attributes}, valid_session
        assigns(:location_destination).should eq(destination)
      end

      it "redirects to the location_destination" do
        destination = Location::Destination.create! valid_attributes
        put :update, {:id => destination.to_param, :location_destination => valid_attributes}, valid_session
        response.should redirect_to(destination)
      end
    end

    describe "with invalid params" do
      it "assigns the location_destination as @location_destination" do
        destination = Location::Destination.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Location::Destination.any_instance.stub(:save).and_return(false)
        put :update, {:id => destination.to_param, :location_destination => {  }}, valid_session
        assigns(:location_destination).should eq(destination)
      end

      it "re-renders the 'edit' template" do
        destination = Location::Destination.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Location::Destination.any_instance.stub(:save).and_return(false)
        put :update, {:id => destination.to_param, :location_destination => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested location_destination" do
      destination = Location::Destination.create! valid_attributes
      expect {
        delete :destroy, {:id => destination.to_param}, valid_session
      }.to change(Location::Destination, :count).by(-1)
    end

    it "redirects to the location_destinations list" do
      destination = Location::Destination.create! valid_attributes
      delete :destroy, {:id => destination.to_param}, valid_session
      response.should redirect_to(location_destinations_url)
    end
  end

end
